- src/scripts/methods/createPopup.ts
Not much to this PR, but `classList.add` won't take multiple classes, so iterate over classes after `split(" ")`.
thanks for the great open source library!
> Allow adding multiple modifier classes to popups, space separated

- package/src/index.d.ts
- package/src/scripts/methods/destroyCalendar.ts
- package/src/scripts/methods/initCalendar.ts
- package/src/scripts/vanilla-calendar.ts
- package/src/types.ts
Add `HTMLOriginalElement` - the original html element, without modifications.
Add `destroy()` - Destroy the calendar instance and its event listeners. #141
> Add a calendar destroy method

- package/src/styles/vanilla-calendar.layout.css
> Safari 12: height: 100%; accepts the entire height of the parent.

- package/src/scripts/helpers/getLocale.ts
> Fix Firefox 52 gets wrong data from getLocaleMonth() / getLocaleWeekday()

- demo/pages/input/main.ts
- examples/additional-features-date-picker-in-input-div.ts
- package/src/scripts/methods/createDays.ts
- package/src/scripts/methods/createWeek.ts
- package/src/scripts/methods/createWeekNumbers.ts
- using `textContent` is fully CSP safe and has the same effect which is to clear the element content
- more PRs will follow (after this PR is merged) to become more CSP safe
- as per MDN [textContent](https://developer.mozilla.org/en-US/docs/Web/API/Node/textContent) docs
> Warning: Setting `textContent` on a node removes all of the node's children and replaces them with a single text node with the given string value.
> chore: clear html with `textContent` to be more CSP safe

- package/src/scripts/handles/handleInput.ts
- the method `setPositionCalendar` is sometime called within a `setTimeout` and in some cases the picker might have been destroyed before the repositioning starts and when that happens it could throws an error that reading `input.offsetHeight` is invalid.
for example, in my use case I opened a Modal window that has a form and one of the input has vanilla-calendar attached to it. If I click on the input to open the calendar picker and then close the modal window without closing calendar, it throws the error because the modal container is where the calendar was associated and but ended up being removed before the calendar has time to call the `setPositionCalendar` (because it was delayed by the `setTimeout`)
> fix: make sure picker exists before repositioning it

- docs/en/reference/main/main-settings.mdx
- docs/ru/reference/main/main-settings.mdx
- package/src/scripts/default.ts
- package/src/scripts/helpers/setVariables.ts
- package/types.ts
- default to `false` and when enabled, it will only be effective on the first selected date and also only work when `selected.month` and `selected.year` are both undefined
- fixes issue #250 (number 2 of discussion #244)
- it could be renamed to `gotoSelection` if you prefer
> feat: add `jumpToSelectedDate` option

- docs/en/reference/additionally/settings.mdx
- docs/ru/reference/additionally/settings.mdx
- package/src/scripts/helpers/getLocalDate.ts
- package/src/scripts/helpers/setVariables.ts
- package/types.ts
- fixes number 4 of Discussion #244 by providing a `'today'` shortcut
- for example: `range: { min: 'today' }` or `selected: { dates: ['2001-02-04', 'today'] }`
> feat: add `'today'` as a shortcut to range min/max date

- docs/en/reference/additionally/settings.mdx
- docs/en/reference/main/main-settings.mdx
- docs/ru/reference/additionally/settings.mdx
- docs/ru/reference/main/main-settings.mdx
- package/src/scripts/helpers/parseDates.ts
- package/types.ts
- in theory it also allow epoch timestamp (`number`) just because timestamp can be provided to `Date`
- fixes number 3 of Discussion #244
> feat: allow providing `Date` to min/max and selected dates

- package/src/scripts/handles/handleInput.ts
- package/src/scripts/methods/createDays.ts
- package/src/scripts/methods/createMonths.ts
- package/src/scripts/methods/createWeek.ts
- package/src/scripts/methods/createWeekNumbers.ts
- package/src/scripts/methods/createYears.ts
- the `.append()` function is not compatible in Salesforce but `.appendChild()` is working fine and does the exact same thing in this context
> fix: use `.appendChild` for cross platform compatibility

- docs/en/reference/additionally/settings.mdx
- docs/ru/reference/additionally/settings.mdx
- package/src/scripts/default.ts
- package/src/scripts/handles/handleDayRangedSelection.ts
- package/src/scripts/methods/createDays.ts
- package/types.ts
- when using `multiple-ranged`, it will by default push **all** the range dates in the `settings.selected.dates`, however in some cases we are sometime only interested in the Start/End dates (first & last). For example, if we have a range of Jan 1st to Feb 28, it will push 59 days to the `settings.selected.dates` array, however with `edgesOnly`, it will only push 2 dates in the array which are equal to the Start/End dates
- for a project like mine with a data grid, I'm only interested in the Start/End dates so that I can use it to filter my grid data by comparing dates between X start date and Y end date. So I'm really only interested in the edges (start/end) and I don't care about the dates that are in the middle, I really don't need to know what the dates are in the middle dates since …
> feat: add new `edgesOnly` to return only start/end dates in selection range

- package/package.json
- Vite was throwing this error which was a problem identified in the package exports, we can use the `*` wildcard to include any file from that folder
> "vanilla-calendar.min" when using `@import vanilla-calendar.min` (without the file extension). We can simply use the * wildcard to fix the issue
if you go on [Are the types wrong?](https://arethetypeswrong.github.io/?p=vanilla-calendar-pro), you can see that the CSS are showing are resolution failed. This PR fixes this problem which is detected when using ViteJS
> fix: ViteJS has problems finding CSS file from package exports

- package/src/scripts/destroy.ts
- fixes another cross platform compatibility issue
- `replaceWith` doesn't seem to be supported in the Salesforce environment (throws an error), we can simply add checks to make sure it is a function that exists before trying to call the function
> fix: cross platform compatibility, make sure `replaceWith()` exists before using it

- docs/en/reference/additionally/settings.mdx
- docs/en/reference/main/main-settings.mdx
- docs/ru/reference/additionally/settings.mdx
- package/src/scripts/handles/handleClickWeekNumber.ts
- package/src/scripts/handles/handleInput.ts
- package/src/scripts/helpers/getColumnID.ts
- package/src/scripts/helpers/position.ts
- package/src/scripts/methods/createMonths.ts
- package/types.ts
- the `auto` will calculate available space on all sides and will always try to position itself to the bottom but when there's not enough space, it will then use the other best position
- also note that the way it works is that after calculating the available spaces, it will then use the code already exists for `positionToInput`, for example the new function `getAvailablePosition()` will return an object with something like the following:
```ts
{
canShow: {top: true, bottom: true, left: false, right: true}
parentPositions: ['top', 'left']
}
```
We can see that the `parentPosition` is something that we can then provide to the `positionToInput` because it uses the same structure. 
Below are a couple of animated gifs of the auto-positioning depending on available space
> feat: add `auto` option to `positionToInput` for auto-positioning

- demo/pages/input/index.html
- demo/pages/input/main.ts
- package/index.d.ts
- package/src/scripts/default.ts
- package/src/scripts/handles/handleInput.ts
- package/src/scripts/helpers/createCalendarToInput.ts
- package/src/scripts/helpers/position.ts
- package/src/scripts/update.ts
- package/types.ts
fixes #274 
- the fix is basically to make sure that the picker element is created **before** the `.update()` does its execution, if the picker element is not yet created then it will be created and then the update runs its execution.
- the code changes are mainly the following
1. move the `setPositionCalendar` function from `handleInput.ts` into `position.ts` so it could be reused by other files
2. move the `createCalendarToInput` function from `handleInput.ts` into a new file named `createCalendarToInput.ts` so it could be reused by other files
3. then the script `update.ts` can now call `createCalendarToInput` to create the picker if it wasn't yet created
for more info about the bug, visit issue #274, the animated gif below simply shows that the input element is no longer being …
> fix: make sure to create picker before calling update(), fixes #274

- docs/en/reference/additionally/settings.mdx
- docs/en/reference/main/main-settings.mdx
- docs/ru/reference/additionally/settings.mdx
- docs/ru/reference/main/main-settings.mdx
- package/src/scripts/default.ts
- package/src/scripts/helpers/setVariables.ts
- package/types.ts
> [FIX] settings.range.min and settings.range.max do not inherit manually set date.min and date.max

- package/src/scripts/helpers/position.ts
- most probably fixes this [issue](https://github.com/uvarov-frontend/vanilla-calendar-pro/pull/278#issuecomment-2288370340) and the issue shown below
- as reported by a user, if the input is a bit outside of the body viewport (ie, when the div is scrolled) then the picker was being positioned to an invalid coordinate because the picker is always appended to the document body which doesn't usually have any scroll and when that happened the calendar picker wasn't showing correctly because it also uses CSS flexbox and the picker started to stretch because it didn't have enough space in the body... so we can simply reposition it to be exactly on the body side (body width - picker picker becomes the new X coordinate)
- so because it doesn't have enough space and because it uses flexbox, it …
> fix: make sure picker position is never outside body viewport

- docs/en/learn/getting-started/usage.mdx
- docs/ru/learn/getting-started/usage.mdx
This might help other TypeScript users who want to use Types like I did, so let's add a small section in the docs :)
- adding a new TypeScript section in the ["Getting Started -> Usage"](https://vanilla-calendar.pro/docs/learn/getting-started/usage)
> docs: add TypeScript usage with Types imports demo

- package/public/README.md
looks like you forgot to update this link since you no longer use ko-fi
> docs: replace unused ko-fi funding donate button

- package/src/scripts/creators/createToInput.ts
- package/src/scripts/handles/handleInput.ts
- `queueMicrotask` is apparently not supported in Salesforce (which is weird), so for better cross-compatibility using `setTimeout` works in all environments (including Salesforce)
- another option might be to use a function to check if it's available or fallback to `setTimeout` when not available, but I think it's overkill for this project (I did implement this in my own project though, let me know if you would rather have that approach as seen below)
```ts
export function queueMicrotaskOrSetTimeout(callback: () => void): void {
try {
queueMicrotask(callback);
} catch {
setTimeout(callback, 0);
}
}
```
> fix: use `setTimeout` for cross-compatibility
