src/classes.ts, src/scripts/methods/clickCalendar.ts, src/scripts/methods/hoverDays.ts, src/styles/vanilla-calendar.scss, src/types.ts
=> Highlighting the date range on hover, before I click to select the second date

src/index.html, src/scripts/methods/clickCalendar.ts, src/scripts/vanilla-calendar.ts, src/styles/vanilla-calendar.scss, src/types.ts
=> Week number clickable

src/scripts/methods/hoverDays.ts
=> Hotfix highlighting the date range on hover

src/scripts/methods/clickCalendar.ts, src/scripts/methods/hoverDays.ts
=> Add the ability to deselect a date range

src/scripts/methods/createDays.ts, src/scripts/methods/createWeekNumbers.ts, src/scripts/vanilla-calendar.ts, src/types.ts
=> Do not create days from past and future months

src/scripts/methods/createDays.ts, src/scripts/vanilla-calendar.ts, src/types.ts
=> Add option to turn off past days

src/scripts/helpers/parserDates.ts, src/scripts/methods/clickCalendar.ts, src/scripts/methods/createDays.ts, src/scripts/methods/hoverDays.ts, src/scripts/methods/setVariablesDates.ts, src/types.ts
=> Add the ability to specify a date range for all date arrays

src/scripts/methods/handlerMultipleRanged.ts, src/scripts/methods/setVariablesDates.ts, src/scripts/vanilla-calendar.ts, src/types.ts
=> Option to only select ranges that are continuously enabled

src/scripts/methods/createDays.ts, src/scripts/vanilla-calendar.ts, src/types.ts
=> Disable days of the week

package/src/index.d.ts, package/src/scripts/main.ts, package/src/scripts/methods/changeMonth.ts, package/src/scripts/methods/controlArrows.ts, package/src/types.ts
Closes #101 
Added a parameter responsible for the number of switchable months. Default is 1.
=> Add jumpMonths

package/src/scripts/helpers/getColumnID.ts
=> Fix year selection in type: 'multiple'

docs/en/reference/additionally/settings.mdx, docs/ru/reference/additionally/settings.mdx, package/src/scripts/methods/showMonth.ts, package/src/scripts/methods/showYear.ts, package/src/types.ts
Added 'only-arrows'.
Closes #121
=> Add the ability to control how you are allowed to switch month and year.

package/src/scripts/methods/handlerInput.ts
=> Hotfix hidden "calendar-input"

package/src/scripts/methods/handlerInput.ts
=> Fix setPositionCalendar

demo/pages/input/main.ts, demo/pages/multiple/main.ts, package/index.d.ts, package/src/scripts/default.ts, package/src/scripts/handles/handleClickArrow.ts, package/src/scripts/handles/handleClickDay.ts, package/src/scripts/handles/handleClickMonthOrYear.ts, package/src/scripts/handles/handleClickWeekNumber.ts, package/src/scripts/helpers/actionsInput.ts, package/src/scripts/methods/changeTime.ts, package/src/scripts/methods/createDays.ts, package/src/vanilla-calendar.ts, package/types.ts
Arguments in all actions have been changed.
Now in each action you can get an instance of the initialized calendar.
=> Add self to actions

package/src/scripts/handles/handleInput.ts
=> Fix #189 Date selection doesn't work with input: true.

package/src/styles/vanilla-calendar.layout.css
=> Fix responsive CSS for several months

package/classes.ts, package/src/scripts/handles/handleInput.ts, package/src/styles/themes/dark.css, package/src/styles/themes/light.css, package/src/styles/vanilla-calendar.layout.css, package/types.ts
=> Revert "Bugfix/201_calendar_position"

docs/en/reference/main/main-settings.mdx, docs/ru/reference/main/main-settings.mdx, package/src/scripts/default.ts, package/src/scripts/helpers/parseComponent.ts, package/src/scripts/methods/createTime.ts, package/types.ts
- should fix number 7 of Discussion #244 to be more CSP (Content Security Policy) compliant
=> feat: add `sanitizer` option to be CSP safe

docs/en/reference/main/main-settings.mdx, docs/ru/reference/main/main-settings.mdx, package/index.d.ts, package/src/scripts/default.ts, package/src/scripts/handles/handleDaySelection.ts, package/types.ts
- new option accepts a boolean or a callback returning a boolean
- should fix number 6 of Discussion #244
- the idea came from Air Datepicker [toggleSelected](https://air-datepicker.com/docs)
=> feat: add new `toggleSelected` option

package/src/styles/vanilla-calendar.layout.css
=> Fix "Button outline obscured by adjacent button. #263"

package/src/scripts/handles/handleInput.ts
=> Add focus event listener and handle esc key

config/styles.config.ts, config/utilities.config.ts, config/vanilla-calendar.config.ts
=> Add version number to the builds

demo/index.css, demo/pages/input/index.html, demo/pages/input/main.ts, package/src/scripts/helpers/position.ts, package/src/scripts/methods/createPopup.ts, package/src/styles/themes/dark.css, package/src/styles/themes/light.css, package/src/styles/vanilla-calendar.layout.css
fixes #235
- at this point, it's mostly just a POC, there's more work to do but the concept works
- things that could be improved
- the calculation I used to offset the pop-up could be improved
- do we want an extra options to disable the auto-position? because the new code will always auto-position the pop-up
- the arrow is not correctly aligned when the pop-up is not positioned at its default position
=> fix: auto-position Pop-ups, fixes #235

demo/pages/input/main.ts, package/src/scripts/methods/reset.ts, package/src/scripts/methods/set.ts, package/src/scripts/methods/update.ts
=> Fix set method for input

demo/pages/lang/main.ts, package/src/scripts/creators/createYears.ts, package/src/scripts/utils/initVariables/initSelectedMonthYear.ts
=> Fix empty list of years with enableJumpToSelectedDate

package/src/scripts/creators/createDates/setDateModifier.ts, package/src/scripts/handles/handleSelectDateRange/handleHoverDatesEvent.ts, package/src/scripts/handles/handleSelectDateRange/toggleHoverEffect.ts, package/src/styles/layout.css
=> Fix display of data-vc-date-selected and data-vc-date-hover attributes

package/src/scripts/handles/handleSelectDateRange/handleHoverDatesEvent.ts, package/src/scripts/handles/handleSelectDateRange/optimizedHandles.ts
https://github.com/uvarov-frontend/vanilla-calendar-pro/issues/372
=> fix: allow onHover logic for dates to work with Web components

package/src/scripts/utils/initVariables/initRange.ts, package/src/scripts/utils/initVariables/initSelectedMonthYear.ts, package/src/scripts/utils/resolveDate.ts
=> fix: Add displayClosestValidDate
